import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar/Navbar";
import CategoriesBar from "./components/CategoriesBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Flopkart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar />
      <CategoriesBar />
      {children}</body>
    </html>
  );
}
